FROM node:20-alpine as development
WORKDIR /app
COPY tsconfig*.json package*.json ./
RUN npm ci
COPY src/ src/
RUN npm run build

FROM node:20-alpine as production
WORKDIR /app
COPY package*.json ./
RUN npm ci --omit=dev
COPY --from=development /app/dist/ ./dist/
EXPOSE 3000
CMD [ "node", "dist/main.js" ]
